monolog:
    channels: ["mailer", "auth"]

    handlers:
        auth:
            type: rotating_file
            path: "%kernel.logs_dir%/auth.log"
            level: error
            max_files: 14
            date_format: "Y-m-d"
            formatter: monolog.formatter.line
            channels: [ "auth" ]
        mailer:
            type: rotating_file
            path: "%kernel.logs_dir%/mailer.log"
            level: error
            max_files: 14
            date_format: "Y-m-d"
            formatter: monolog.formatter.line
            channels: [ "mailer" ]

        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            max_files: 14
            date_format: "Y-m-d"
            formatter: monolog.formatter.line

        # opcjonalnie osobny log tylko dla critical (500 + fatal)
        critical:
            type: rotating_file
            path: "%kernel.logs_dir%/critical.log"
            level: critical
            max_files: 30
            date_format: "Y-m-d"
